name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      
      - name: Install dependencies
        run: npm ci
      
      - name: Inject env vars
        run: |
          echo "VITE_NEWS_API_KEY=${{ secrets.VITE_NEWS_API_KEY }}" >> .env
          echo "VITE_GUARDIAN_API_KEY=${{ secrets.VITE_GUARDIAN_API_KEY }}" >> .env
          echo "VITE_NYTIMES_API_KEY=${{ secrets.VITE_NYTIMES_API_KEY }}" >> .env
      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FEED_FLASH }}
          channelId: live
          projectId: feed-flash
